receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      network:
      paging:
      processes:
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
        mute_process_cgroup_error: true
        metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true
  hostmetrics/disk:
    collection_interval: 1m
    scrapers:
      disk:
      filesystem:
      
exporters:
 otlphttp:
    endpoint: https://otel.flightctl.edge-devices.net:443
    tls:
      insecure: false
      insecure_skip_verify: true

processors:
  batch: {}
  attributes:
    actions:
      - action: insert
        key: device
        value: fitlet2
  memory_limiter:
    check_interval: 10s
    limit_percentage: 5
    spike_limit_percentage: 1

service:
  pipelines:
    metrics:
      receivers: [hostmetrics,hostmetrics/disk]
      processors: [batch, memory_limiter, attributes]
      exporters: [otlphttp]