kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-ws-connector
  namespace: edge-ws-connector
  labels:
    app: edge-ws-connector
spec:
  replicas: 0
  selector:
    matchLabels:
      app: edge-ws-connector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edge-ws-connector
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: edge-ws-connector
          env:        
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-ws-connector
                  key: PORT
            - name: CLI_PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-ws-connector
                  key: CLI_PORT
            - name: WS_MANAGER
              valueFrom:
                configMapKeyRef:
                  name: edge-ws-connector
                  key: WS_MANAGER
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/edge-ws-connector:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600