FROM quay.io/centos-bootc/centos-bootc:stream9
ADD etc etc
RUN rm -rf /opt && \
    mkdir -p /opt/cni

RUN dnf install -y microshift flightctl-agent && \
    systemctl enable microshift.service && \
    systemctl enable flightctl-agent.service

## Uncomment to add your own ssh key
# COPY replace_rsa.pub /usr/etc-system/root.keys
# RUN touch /etc/ssh/sshd_config.d/30-auth-system.conf; \
#     mkdir -p /usr/etc-system/; \
#     echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf; \
#     chmod 0600 /usr/etc-system/root.keys
# VOLUME /var/roothome

## Add your flightctl configuration and certificates
ADD config.yaml /etc/flightctl/
ADD ca.crt /etc/flightctl
ADD client-enrollment.* /etc/flightctl/
