FROM quay.io/fedora/fedora-bootc:41

RUN dnf -y install dnf5-plugins && \
    dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service

# ADD config.yaml /etc/flightctl/
