FROM quay.io/fedora/fedora-bootc:41

RUN dnf -y install dnf5-plugins && \
    dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service

# Fix for "no default root filesystem type specified in container"
RUN mkdir -p /usr/lib/bootc/install && cat <<-'EOF' > /usr/lib/bootc/install/00-fedora.toml
[install]
root-fs-type = "xfs"
kargs = ["audit=0"]
EOF

# ADD config.yaml /etc/flightctl/
