apiVersion: v1alpha1
kind: Fleet
metadata:
  name: basic-nginx-fleet
spec:
  selector:
    matchLabels:
      fleet: basic-nginx-fleet
  template:
    spec:
      os:
        image: quay.io/flightctl/flightctl-agent-basic-nginx:latest
      config:
        - name: motd-update
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
        - name: microshift-manifests
          gitRef:  
            repository: basic-nginx-demo
            targetRevision: main
            path: /demos/basic-nginx-demo/configuration
        - name: ricky-super-secrets
          gitRef:  
            repository: ricky-super-secrets
            targetRevision: main
            path: /configuration
      systemd:
        matchPatterns:
          - "microshift.service"
          - "crio.service"
          - "flightctl-agent.service"
