{
 "title": "RHDE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk IO time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_disk_io_time_seconds_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "process_memory_utilization_ratio{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}