apiVersion: v1alpha1
kind: Fleet
metadata:
  name: mlops-pins-fleet
spec:
  selector:
    matchLabels:
      fleet: mlops-pins-fleet
  template:
    spec:
      os:
        image: quay.io/oglok/flightctl-agent-centos:latest

      config:
        - name: model-server
          gitRef:
            repository: default-repo
            targetRevision: main
            path: /inverter-fleet/deployment-manifests/

      systemd:
       matchPatterns:
        - inverter.service
        - rs485-protocol.service

