enrollment-service:
  authentication:
    client-certificate: certs/client-enrollment.crt
    client-key: certs/client-enrollment.key
  service:
    certificate-authority: certs/ca.crt
    server: https://agent-api.flightctl.edge-devices.net
  enrollment-ui-endpoint: https://ui.flightctl.edge-devices.net
grpc-management-endpoint: grpcs://agent-grpc.flightctl.edge-devices.net
spec-fetch-interval: 0m10s
status-update-interval: 0m10s
tpm-path: /dev/tpmrm0
