---
receivers:
  journald:
    directory: /run/log/journal
    units:
      - ssh
      - microshift
      - opentelemetry-collector
      - inverter
      - rs485-protocol
    priority: info
  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
  prometheus/self:
    config:
      scrape_configs:
        - job_name: ‘agent’
          scrape_interval: 10s
          static_configs:
            - targets: [‘127.0.0.1:8888’]

processors:
  resourcedetection/system:
    detectors: ["system"]
  batch:

exporters:
  debug:
    verbosity: info

extensions:
  health_check:
  file_storage:
    directory: /cache
    timeout: 2s
    compaction:
      on_start: true
      directory: /tmp/
      max_transaction_size: 65_536
    fsync: false


service:
  extensions: [health_check, file_storage]
  pipelines:
    metrics:
      receivers: [hostmetrics, prometheus/self]
      processors: [resourcedetection/system, batch]
      exporters: [debug]
    logs:
      receivers: [journald]
      processors: [resourcedetection/system, batch]
      exporters: [debug]
