FROM quay.io/flightctl-demos/centos-bootc:latest

ADD etc etc

RUN dnf install -y opentelemetry-collector

ADD opentelemetry-collector.service /usr/lib/systemd/system/

RUN systemctl enable opentelemetry-collector.service

## ----------------- IMPORTANT -----------------
## We need to add certs (ca.crt, client.crt & client.key) to the local directory etc/opentelemetry-collector/certs
## Also we need to add the FlightCTL config.yaml to the local directory etc/flighctl/config.yaml
## ---------------------------------------------

RUN chown -R observability:observability /etc/opentelemetry-collector

RUN rm -rf /opt && ln -s /var /opt
RUN [ ! -L /var/run ] && [ -d /var/run ] && rm -rf /var/run && ln -s /run /var/ || ln -s /run /var/run