FROM quay.io/flightctl-demos/centos-bootc:latest

ADD etc etc

RUN dnf install -y opentelemetry-collector

ADD opentelemetry-collector-rhde.service /usr/lib/systemd/system/

RUN systemctl enable opentelemetry-collector-rhde.service

RUN /usr/bin/getent group rhde-observability > /dev/null || /usr/sbin/groupadd -r rhde-observability && \
    /usr/bin/getent passwd rhde-observability > /dev/null || /usr/sbin/useradd -r -M -s /sbin/nologin -g rhde-observability -G systemd-journal rhde-observability

## ----------------- IMPORTANT -----------------
## We need to add certs (ca.crt, client.crt & client.key) to the local directory etc/opentelemetry-collector-rhde/certs
## Also we need to add the FlightCTL config.yaml to the local directory etc/flighctl/config.yaml
## ---------------------------------------------

RUN rm -rf /opt && ln -s /var /opt
RUN [ ! -L /var/run ] && [ -d /var/run ] && rm -rf /var/run && ln -s /run /var/ || ln -s /run /var/run