apiVersion: v1beta1
kind: Fleet
metadata:
  name: quadlet-wordpress-fleet
spec:
  selector:
    matchLabels:
      fleet: quadlet-wordpress-fleet
  template:
    spec:
      os:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
      config:
        - name: motd-update
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
        - name: quadlets
          gitRef:  
            repository: quadlet-wordpress-demo
            targetRevision: main
            path: /demos/quadlet-wordpress-demo/configuration
      systemd:
        matchPatterns:
          - "wordpress-app.service"
          - "wordpress-db.service"
