{
 "title": "RHDE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_id",
    "label": "host_id",
    "query": {
     "query": "label_values(process_cpu_time_seconds_total,host_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk IO time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_disk_io_time_seconds_total{host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_memory_utilization_ratio{host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}