name: "Build Bootc Agent Bootstrap Images"
on:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

env:
  REGISTRY: quay.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        flavor: [centos, fedora, rhel]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Modify Containerfile
        run: |
          pushd bootc-agent-images/${{ matrix.flavor }}
          echo "${{ secrets.FLIGHTCTL_RSA_PUB }}" > flightctl_rsa.pub
          sed -i -e 's/^# COPY flightctl_rsa.pub \/usr\/etc-system\/root.keys/COPY flightctl_rsa.pub \/usr\/etc-system\/root.keys/' \
                 -e 's/^# RUN touch \/etc\/ssh\/sshd_config.d\/30-auth-system.conf;/RUN touch \/etc\/ssh\/sshd_config.d\/30-auth-system.conf;/' \
                 -e 's/^#     mkdir -p \/usr\/etc-system\/;/    mkdir -p \/usr\/etc-system\/;/' \
                 -e 's/^#     echo '\''AuthorizedKeysFile \/usr\/etc-system\/%u.keys'\'' >> \/etc\/ssh\/sshd_config.d\/30-auth-system.conf;/    echo '\''AuthorizedKeysFile \/usr\/etc-system\/%u.keys'\'' >> \/etc\/ssh\/sshd_config.d\/30-auth-system.conf;/' \
                 -e 's/^#     chmod 0600 \/usr\/etc-system\/root.keys/    chmod 0600 \/usr\/etc-system\/root.keys/' \
                 -e 's/^# VOLUME \/var\/roothome/VOLUME \/var\/roothome/' Containerfile
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.CLIENT_ENROLLMENT_CRT }}" > client-enrollment.crt
          echo "${{ secrets.CLIENT_ENROLLMENT_KEY }}" > client-enrollment.key
          popd

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry.redhat.io
        if: matrix.flavor == 'rhel'
        uses: docker/login-action@v3
        id: rh-login
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}
        continue-on-error: true

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_PASSWORD }}
        continue-on-error: true

      - name: Check login status
        id: login-status
        run: |
          if [ ${{ steps.rh-login.outcome }} == "failure"]; then
            if [
              "${{ secrets.RH_REGISTRY_USERNAME }}" 
              -a "${{ secrets.RH_REGISTRY_PASSWORD }}"
              -a "${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}"
              -a "${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_PASSWORD }}"
            ]; then
              exit 1
            fi

            echo "push_flag=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "push_flag=true" >> "$GITHUB_OUTPUT"
        
      - name: Build image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: bootc-agent-images/${{ matrix.flavor }}
          file: bootc-agent-images/${{ matrix.flavor }}/Containerfile
          load: true
          tags: user/flightctl-agent:test

      - name: Test image
        run: |
          ID=$(docker create ${{ steps.build.outputs.imageid }} /verify-flightctl-agent.sh)
          docker cp .github/workflow-scripts/verify-flightctl-agent.sh $ID:/
          docker start $ID
          exit $(docker inspect $ID --format='{{.State.ExitCode}}')

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: bootc-agent-images/${{ matrix.flavor }}
          file: bootc-agent-images/${{ matrix.flavor }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ fromJSON( steps.login-status.outputs.push_flag ) }}
          tags: ${{ env.REGISTRY }}/${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}/flightctl-agent-${{ matrix.flavor }}:bootstrap
