FROM quay.io/flightctl/flightctl-agent-centos:bootstrap

ADD etc etc

RUN rm -rf /opt && \
    mkdir -p /opt/crio
RUN dnf install -y microshift && \
    systemctl enable microshift.service

RUN mkdir -p /opt/cni && mkdir -p /var/opt/cni/bin && rm -rf /opt/cni/bin && ln -s /var/opt/cni/bin /opt/cni/bin
RUN [ ! -L /var/run ] && rm -rf /var/run && ln -s /run /var/

