FROM quay.io/flightctl/flightctl-agent-centos:bootstrap

ADD etc etc

RUN rm -rf /opt && \
    mkdir -p /opt/crio
RUN dnf install -y microshift && \
    systemctl enable microshift.service


RUN rm -rf /opt && ln -s /var /opt
RUN [ ! -L /var/run ] && rm -rf /var/run && ln -s /run /var/

