apiVersion: v1
kind: Service
metadata:
  name: edge-cam
  namespace: edge-cam
  labels:
    app: edge-cam
spec:
  selector:
    app: edge-cam
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: 8081-tcp